feat: добавить User и Film
Matsidon/java-filmorate pull request #1
Opened 2022-08-08 16:06 UTC by Matsidon

2022-08-09 07:42 UTC, kukolev requested changes

2022-08-09 07:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Integer, Film> filmMap = new HashMap<>();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-09 07:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (isCorrectName(film) && isCorrectDescription(film) && isCorrectDuration(film) && isCorrectReleaseDate(film)) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-09 07:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (isCorrectName(film) && isCorrectDescription(film) && isCorrectDuration(film) && isCorrectReleaseDate(film)) {
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-09 07:42 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return new ArrayList<>(userMap.values());
Бизнес-логика должна быть реализована в сервисах, а не в контроллере. Именно сервис инкапсулирует всю логику работы приложения и выставляет наружу методы, которые потом вызываются из контроллеров или из других сервисов.

Аналогично нужно поправить ниже.

2022-08-09 07:46 UTC, kukolev requested changes

2022-08-09 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Integer, Film> filmMap = new HashMap<>();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-08-09 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (isCorrectName(film) && isCorrectDescription(film) && isCorrectDuration(film) && isCorrectReleaseDate(film)) {
Валидации лучше вынести в отдельный приватный метод. Так код будет понятней.

2022-08-09 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (isCorrectEmail(user) && isCorrectLogin(user) && isCorrectBirthday(user)) {
Валидации лучше вынести в отдельный приватный метод. Так код будет понятней.

2022-08-09 07:46 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    boolean isCorrectEmail(@RequestBody User user) {
Метод нужно сделать приватным, т.к. он является вспомогательными и не нужно, чтобы к нему был доступ извне.

Аналогично нужно поправить методы ниже.

2022-08-10 13:32 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return new ArrayList<>(userMap.values());
Спасибо, добавила логику в сервисы.

2022-08-10 13:32 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    Map<Integer, Film> filmMap = new HashMap<>();
Исправила

2022-08-10 13:32 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    boolean isCorrectName(@RequestBody Film film) {
Исправила

2022-08-10 13:32 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    boolean isCorrectEmail(@RequestBody User user) {
Исправила

2022-08-10 13:33 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (isCorrectEmail(user) && isCorrectLogin(user) && isCorrectBirthday(user)) {
Добавила метод

2022-08-10 13:33 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        if (isCorrectEmail(user) && isCorrectLogin(user) && isCorrectBirthday(user)) {
Добавила метод

2022-08-10 13:33 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    Map<Integer, User> userMap = new HashMap<>();
Исправила

2022-08-10 13:33 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (isCorrectName(film) && isCorrectDescription(film) && isCorrectDuration(film) && isCorrectReleaseDate(film)) {
Добавила метод

2022-08-10 17:18 UTC, kukolev requested changes

2022-08-10 17:18 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return film.getReleaseDate().isAfter(LocalDate.of(1895, 12, 28));
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-08-10 17:19 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        return new ArrayList<>(userMap.values());
Здесь я немного забежал вперед. На данном этапе вам не обязательно было выделять логику в сервис, это требования к будущим спринтам. Но при этом получилось хорошо, будущий материал будет даваться проще.

2022-08-11 22:37 UTC, kukolev approved these changes

2022-08-18 19:29 UTC, merged