Sprint 2
Matsidon/java-filmorate pull request #2
Opened 2022-08-25 16:17 UTC by Matsidon

feat: добавить friends и likes

2022-08-26 07:05 UTC, kukolev requested changes

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorResponse.java
> +    private final String error;
Это поле не имеет смысла, т.к. нигде не используется - только задается в конструкторе. Следовательно поле можно удалить и упростить код.

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (NullPointerException e) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } catch (NullPointerException e) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-08-26 07:05 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-08-26 19:11 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        } catch (NullPointerException e) {
Спасибо, поправила.

2022-08-27 07:23 UTC, kukolev requested changes

2022-08-27 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        return filmStorage.getAllFilms().stream().sorted((o1, o2) -> -1 * (o1.getLikes().size() - o2.getLikes().size()))
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину.

2022-08-27 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(userId) != null && userStorage.getUserById(otherId) != null) {
Этот алгоритм можно упростить, если использовать HashMap, где ключом будет ID друга, а значением будет счетчик. Если счетчик == 2, то друг встретился у обоих пользователей. Такой алгоритм будет работать за O(n) против O(n^2)

2022-08-27 14:44 UTC, Matsidon commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(userId) != null && userStorage.getUserById(otherId) != null) {
Спасибо. Поняла насчет сложности, сделала за O(n), правда, с несколько иной реализацией получилось. Напишите, пожалуйста, если мой вариант менее эффективный- поправлю.

2022-08-27 21:33 UTC, kukolev approved these changes

2022-08-27 21:35 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (userStorage.getUserById(userId) != null && userStorage.getUserById(otherId) != null) {
Да, этот вариант тоже хороший. По моему даже проще моего получилось!

2022-08-29 13:37 UTC, merged